services:
  apifunkoscs:
    image: apifunkoscs
    build:
      context: .
      dockerfile: ApiFunkosCS/Dockerfile

  mongo-db:
    container_name: tienda-mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass"
      MONGO_INITDB_DATABASE: "tienda"
    volumes:
      - mongo-init:/data/db
      - ./ApiFunkosCS/initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"

volumes:
  mongo-init: